version: '3.8'

services:
  central_service:
    build: ./Services/CentralService
    ports:
      - "8000:5000"

  sentiment_analysis:
    build: ./Services/SentimentAnalysisService
    ports:
      - "8001:5002"

  word_count:
    build: ./Services/WordCountService
    ports:
      - "8002:5003"

  entity_recognition:
    build: ./Services/EntityRecognitionService
    ports:
      - "8003:5001"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - central_service
      - sentiment_analysis
      - word_count
      - entity_recognition

